apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine
  labels:
    app: engine
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: engine
        qix-engine: ""
    spec:
      containers:
      - name: engine
        image: qlikea/engine:12.119.0
        imagePullPolicy: IfNotPresent
        args: ["-S", "ValidateJsonWebTokens=2", "-S", "JsonWebTokenSecret=Insert-Long-GUID-For-JWT-Secret"]
        ports:
        - containerPort: 9076
        - containerPort: 9090
        volumeMounts:
        - name: doc-volume
          mountPath: /doc
        - name: data-volume
          mountPath: /data
      volumes:
      - name: doc-volume
        hostPath:
          path: /home/azureuser/doc
      - name: data-volume
        hostPath:
          path: /home/azureuser/csv
      imagePullSecrets:
      - name: dockerhub
